<?php

namespace ContainerKQXbp0C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WhORrNVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.whORrNV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.whORrNV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthenticationController::login' => ['privates', '.service_locator.Lg7M_Sj', 'get_ServiceLocator_Lg7MSjService', true],
            'App\\Controller\\AuthenticationController::register' => ['privates', '.service_locator.Lg7M_Sj', 'get_ServiceLocator_Lg7MSjService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AuthenticationController:login' => ['privates', '.service_locator.Lg7M_Sj', 'get_ServiceLocator_Lg7MSjService', true],
            'App\\Controller\\AuthenticationController:register' => ['privates', '.service_locator.Lg7M_Sj', 'get_ServiceLocator_Lg7MSjService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AuthenticationController::login' => '?',
            'App\\Controller\\AuthenticationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthenticationController:login' => '?',
            'App\\Controller\\AuthenticationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
