<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ8rtv17\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ8rtv17/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ8rtv17.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ8rtv17\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ8rtv17\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q8rtv17',
    'container.build_id' => 'b1e09d5c',
    'container.build_time' => 1712595459,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ8rtv17');
