<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxjV3Sv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxjV3Sv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxjV3Sv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxjV3Sv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxjV3Sv\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxjV3Sv',
    'container.build_id' => 'f5f8749d',
    'container.build_time' => 1716211451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxjV3Sv');
