<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKQXbp0C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKQXbp0C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKQXbp0C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKQXbp0C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKQXbp0C\App_KernelDevDebugContainer([
    'container.build_hash' => 'KQXbp0C',
    'container.build_id' => '03545100',
    'container.build_time' => 1715609126,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKQXbp0C');
