<?php

namespace ContainerYjerYsz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemMapperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Mapper\ItemMapper' shared autowired service.
     *
     * @return \App\Mapper\ItemMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Mapper/ItemMapper.php';

        return $container->privates['App\\Mapper\\ItemMapper'] = new \App\Mapper\ItemMapper();
    }
}
