<?php

namespace ContainerT1KeSTB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNFTItemControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\NFTItemController' shared autowired service.
     *
     * @return \App\Controller\NFTItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/NFTItemController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/UploadImageService.php';

        $container->services['App\\Controller\\NFTItemController'] = $instance = new \App\Controller\NFTItemController(($container->privates['App\\Service\\UploadImageService'] ?? ($container->privates['App\\Service\\UploadImageService'] = new \App\Service\UploadImageService(($container->services['kernel'] ?? $container->get('kernel', 1))))));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\NFTItemController', $container));

        return $instance;
    }
}
